### ISSUE TITLE
Aedes-persistence-level inserts data in batches using addSubscriptions and fails 

### ISSUE THREAD

**Issue by v-divya110** [mcollina/aedes-persistence-level#11]
When aedes-persistence-level restarts, the code 
```
pump(this._db.createValueStream({
    gt: SUBSCRIPTIONS,
    lt: SUBSCRIPTIONS + '\xff',
    valueEncoding: msgpack
  }), through.obj(function (chunk, enc, cb) {
    trie.add(chunk.topic, chunk)
    cb()
  })
``` fails. 
Chunk returned is 91 and chunk.topic is undefined.

**Comment by mcollina** [comment]
I’m a bit low on time for fixing this. Would you mind sending a PR?

**Comment by v-divya110** [comment]
Sure I could send a PR, but fixing this leads to problems in other areas of aedes-persistence-level. I have finally come up with a fix for all the problems in aedes-persistence-level and I would like to send a PR too but it includes a lot of changes. Its a combination of 4 issues I found. Will it be okay for you?

**Comment by v-divya110** [comment]
PR sent ! However on the way I had more and more issues in the same package so the PR includes fixes for all of these issues.
