### ISSUE TITLE
removeSubscriptions error

### ISSUE THREAD

**Issue by marvinroger** [mcollina/aedes-persistence-level#2]
[Line 164](https://github.com/mcollina/aedes-persistence-level/blob/master/persistence.js#L164), if `resubs` is empty, you're affecting it `null`. [Line 206](https://github.com/mcollina/aedes-persistence-level/blob/master/persistence.js#L206), you're considering `subs` is always an array, which is not the case as it can be null.

Basically, a `TypeError: Cannot read property 'map' of null` error appears with an empty database.

**Comment by mcollina** [comment]
of course! Would you mind to send a quick pr? maybe we can even add a unit test about this case to https://github.com/mcollina/aedes-persistence/blob/master/abstract.js

**Comment by marvinroger** [comment]
I would just remove the condition that puts sub to `null`, it seems useless to other parts of the code. Regarding the unit test, I'll let you implement it as I am not familiar enough with aedes ;)
