### ISSUE TITLE
Subscriptions with similar client ID throw error 'no such packet'

### ISSUE THREAD

**Issue by v-divya110** [mcollina/aedes-persistence-level#20]
I have a client with client ID "subscriber1" and I connect this with clean: false and QoS 1 to the topic test/hello/world. I publish messages with QoS 1 to the topic test/hello/world and I use backpressure to avoid sending PUBACKs. After publishing 10 messages, I killed the publisher and subscriber. 
Connect another client with client ID "subscriber", subscriptions for subscriber1 are fetched and outgoingUpdate starts throwing errors "no such packet"

**Comment by ralphtheninja** [comment]
Do you have a code sample that reproduces this behavior?

**Comment by seriousme** [comment]
Can we close this issue ?

**Comment by robertsLando** [comment]
I would close it for now, just feel free to reopen if problem persists in latest version
