### ISSUE TITLE
Crash bug with latest level

### ISSUE THREAD

**Issue by ralphtheninja** [mcollina/aedes-persistence-level#21]
**System Information**
- Aedes: 0.42.5
- NodeJS: 14.12.0
- OS: Ubuntu 20.04 LTS
- Arch: x86_64

**Describe the bug**
`aedes-persistence-level` crashes with latest `level`. 

**To Reproduce**

I've created a repository that reproduces the crash here: https://github.com/ralphtheninja/aedes-crash-with-level
How to reproduce is described in the readme.

**Expected behavior**
It shouldn't crash.

**Additional context**
It only seems to happen when you publish a `qos: 2` message.

**Comment by robertsLando** [comment]
I think that there could be some breaking change in a major level release, could you send a PR for this? Level persistence hasn't been updated for a long time

**Comment by ralphtheninja** [comment]
> I think that there could be some breaking change in a major level release, could you send a PR for this? Level persistence hasn't been updated for a long time

I could. But it would be nice to know what the problem is first and where to apply the fix. Maybe there's a workaround as well?

**Comment by ralphtheninja** [comment]
@vweevers You thought it had something to do with multiple encodings?

**Comment by robertsLando** [comment]
@ralphtheninja It seems something related to: https://github.com/kawanet/msgpack-lite/pull/81

**Comment by robertsLando** [comment]
The error is in this line: https://github.com/moscajs/aedes-persistence-level/blob/master/persistence.js#L398

**Comment by robertsLando** [comment]
You should try to print blob to see the content of blob when it crash

**Comment by robertsLando** [comment]
You could also give a try to: https://github.com/JoshuaWise/tiny-msgpack

**Comment by ralphtheninja** [comment]
The blob content looks like:

![Screenshot from 2020-09-29 10-25-47](https://user-images.githubusercontent.com/308049/94532452-2bbd8280-023e-11eb-8fbf-65e884da38b4.png)

`key` is `incoming:mqttjs_d634c29b:51471`

**Comment by robertsLando** [comment]
@ralphtheninja Please try to add a log also [here](https://github.com/moscajs/aedes-persistence-level/blob/master/persistence.js#L387) so we also see the packet before the encode

**Comment by ralphtheninja** [comment]
```
key: incoming:mqttjs_9bd12a52:29811
newp: Packet {
  cmd: 'publish',
  brokerId: undefined,
  brokerCounter: 0,
  topic: 'foo',
  payload: <Buffer 62 61 72>,
  qos: 2,
  retain: false,
  messageId: 29811
}
```

**Comment by ralphtheninja** [comment]
It seems we store a `Buffer` here https://github.com/moscajs/aedes-persistence-level/blob/master/persistence.js#L387 (what `msgpack.encode()` returns),  but when we get the value back it's a string.

**Comment by ralphtheninja** [comment]
If I pass `{ valueEncoding: 'binary' }` to `level()` before passing it into `aedes-persistence-level` it works. This is a good workaround. Maybe we should update the docs, saying something about using latest level needs to have `valueEncoding` set to `'binary'`.

**Comment by ralphtheninja** [comment]
It also works if I pass `{ valueEncoding: 'binary' }` to `.get()` here https://github.com/moscajs/aedes-persistence-level/blob/master/persistence.js#L392

**Comment by ralphtheninja** [comment]
I think a good start would be to refresh the tests a bit. Maybe throw out `memdown()` and use `level` instead?

**Comment by robertsLando** [comment]
> If I pass { valueEncoding: 'binary' } to level() before passing it into aedes-persistence-level it works. This is a good workaround. Maybe we should update the docs, saying something about using latest level needs to have valueEncoding set to 'binary'.

I think we could add this as an option also to db.get functions. Could you add a PR with this and tell me if it works? 

Check `options` in db.get and db.put: https://github.com/Level/level#dbputkey-value-options-callback

**Comment by ralphtheninja** [comment]
It seems all `.put()` calls store `Buffer` from calls to `msgpack.encode(something)`, which means all `.get()` calls expect a `Buffer` back in the `blob` parameter. So a fix _could_ be to just add `{ valueEncoding: 'binary' }` to all `.get()` calls.

Looking back at the git history @mcollina added `{ valueEncoding: 'binary' }` to streams https://github.com/moscajs/aedes-persistence-level/commit/c30b28ef459ffd45b0e1131efd2980d28f0b0aa7

**Comment by robertsLando** [comment]
> I think a good start would be to refresh the tests a bit. Maybe throw out memdown() and use level instead?

Do it :)

**Comment by ralphtheninja** [comment]
> Check `options` in db.get and db.put: https://github.com/Level/level#dbputkey-value-options-callback

I'm one of the maintainers of `level` so I'm aware of the options, but thanks :)



> I think we could add this as an option also to db.get functions. Could you add a PR with this and tell me if it works?

Sure. But it would be nice to tweak the tests also to use a plain `level` instead of `memdown`, so we can utilize all the nice tests this module already has.

**Comment by robertsLando** [comment]
@ralphtheninja Ok open a PR so. I suggest to create a general `encodingOption` object so we dont have lot `{ valueEncoding: 'binary' }` around the code

Also feel free to remove memdown and bump deps :)

**Comment by robertsLando** [comment]
Last thing: 


Add `match_empty_levels` [here](https://github.com/moscajs/aedes-persistence-level/blob/master/persistence.js#L13
) check: https://github.com/moscajs/aedes-persistence-redis/blob/master/persistence.js#L18

**Comment by ralphtheninja** [comment]
> Add `match_empty_levels` [here](https://github.com/moscajs/aedes-persistence-level/blob/master/persistence.js#L13) check: https://github.com/moscajs/aedes-persistence-redis/blob/master/persistence.js#L18

Is this related to this fix? I can add that as well, but would rather it to be a separate PR.

**Comment by ralphtheninja** [comment]
I just noticed that you use `precommit` hook to run the tests, which is slightly problematic when re-writing tests. Would you guys be extremely upset if I removed the `precommit` hook? I'd like to produce a failing test, and then apply fix after that to see the tests pass. Otherwise everything has to be in a single commit. Makes sense?

**Comment by ralphtheninja** [comment]
I can remove the `precommit` hook temporarily, and then revert that commit in the PR. After we squash everything nicely.

**Comment by robertsLando** [comment]
> I can remove the precommit hook temporarily, and then revert that commit in the PR. After we squash everything nicely.

No need to remove it, just run `mv .git/hooks/pre_commit .git/hooks/pre_commit.bck`

This will disable the pre-commit hook :)

**Comment by ralphtheninja** [comment]
> No need to remove it, just run `mv .git/hooks/pre_commit .git/hooks/pre_commit.bck`
> 
> This will disable the pre-commit hook :)

I noticed this too late :)

**Comment by ralphtheninja** [comment]
~~I'll bump `.travis.yml` as well and get rid of old node versions. We should release a new major.~~

**Comment by robertsLando** [comment]
Could you use girhib actions instead of travis? You can check an example in aedes-persistence-redis/mongodb

**Comment by ralphtheninja** [comment]
> Could you use girhib actions instead of travis? You can check an example in aedes-persistence-redis/mongodb

Sure!

**Comment by ralphtheninja** [comment]
Thanks for swift reply btw and nice to have this fixed! :rocket:

**Comment by robertsLando** [comment]
@ralphtheninja Version 7.0.0 just published :rocket:
