### ISSUE TITLE
How to handle cluster to scalability in mqtt broker?

### ISSUE THREAD

**Issue by Bytesware** [mcollina/aedes-persistence-level#34]
is there a way to increase the scalability? if any only one help me with this?
Currently, it handles 15K subscribers, I need to manage with 2 million.

What is the solution for that to achieve this?

**Comment by robertsLando** [comment]
Just use another persistence like mongo or redis

**Comment by Bytesware** [comment]
> Just use another persistence like mongo or redis

Can you share some examples, how we can achieve this, will be a great help.

**Comment by robertsLando** [comment]
You need a load balancer (like nginx) and multiple instances of aedes or you can use nodejs cluster module that handles load balancing automatically and spawn multiple instances of aedes like in this example: https://github.com/moscajs/aedes/tree/main/examples/clusters

**Comment by Bytesware** [comment]
I tried this code, but is running, when subscriber trying to connect or publisher publish message which not able to connect. Shows in log.

Have you tested code?

 

Thanks,

Rajesh

**Comment by robertsLando** [comment]
> Have you tested code?

Yes, it works
